DROP TABLE IF EXISTS user;
CREATE TABLE users(
    ID SERIAL primary key,
    NAME VARCHAR(50) NOT NULL,
    LASTNAME VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(50) NOT NULL,
    PHONE_NUMBER VARCHAR(20) NOT NULL
);